version: '3.3'
services:
  db_brn:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: brn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  brn:
    container_name: brn
    command: java -jar build/libs/epam-brn.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      PG_USER: admin
      PG_PASSWORD: admin
