name: Frontend tests
on:
  pull_request:
    paths:
    - 'frontend/**'


jobs: 
  deps: 
    name: Run tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install deps
        working-directory: ./frontend
        run: |
          npm install
      - name: Run ember app tests 
        working-directory: ./frontend
        run: |
          npm run test