name: Frontend tests
on:
  pull_request:
    paths:
    - 'frontend/**'


jobs: 
  deps: 
    name: Install dependencies
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
  tests:
    name: Run tests
    needs: deps
    steps: 
      - uses: alexlafroscia/actions-ember-testing@master