name: SonarCloud
on:
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - 'frontend-angular/**'
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install typescript@">=3.2.1 <3.8.0"
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Analyze with SonarCloud
        run: ./gradlew --debug --stacktrace clean build sonarqube
          -Dsonar.pullrequest.key=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          -Dsonar.pullrequest.branch=${PULL_REQUEST_BRANCH}
          -Dsonar.pullrequest.base=${BASE_BRANCH}
          -Dsonar.login=$SONAR_TOKEN_SIESTA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SIESTA }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.base_ref }}